### ISSUE TITLE
Add Makefiles

### ISSUE THREAD

**Issue by jonasliendl** [jonasliendl/c-university-task#4]
## To-Do

- [x] Makefile for sequential program (make run, make clean, make test)
- [x] Makefile for parallel program (make run, make clean, make test)
- [x] Setup test environment
